# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.CharField(default='', max_length=100),
        ),
    ]
