# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170920_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_created',
        ),
    ]
