# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fullname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
